exports.items = [
    'Half Mask x7',
    'A-2607 Knife',
    'Tank Battery',
    'Tank Shell x10',
    'Flash Drive x5',
    'Resperator x4',
    'Bloodset x3',
    'Gas Analyzer x2',
    'Morphine x8',
    'Tushonka x15',
    'Car battery x4',
    'Spark Plug x8',
    'WD-40',
    'Wiper Cleaner x2',
    'Bleach x2',
    'Alkali x2',
    'Hose x4',
    'Propane x2',
    'SG-C10',
    'Virtex x2',
    'Cord x2',
    'T-Plug x4',
    'Circuit Board x5',
    'Graphics Card x3',
    'CPU Fan x8',
    'CPU x3',
    'Rechargable Battery x3',
    'Broken GPhone x3',
    'All Types of Cigerettes x5',
    'Wires x5',
    'Capacitors x5',
    'Blackrock Chest Rig x2',
    'WTRig x2',
    'Fuel Conditioner x4',
    'Shmaska',
    'Lion x2',
    'Horse Figure x2',
    'Cat Figure',
    'Pilgrim Backpack',
    'Royal Wrist Watch',
    'Teapot x3',
    'Vase x2',
    'Golden TT pistol',
    'Killa Helmet',
    'Lab Key Card x3',
    'CMS Kit x2',
    'Defibrillator'
]